mode = "dark"
accent = "#69b1ff"
selection = "#1f3e5e"
muted = "#636363"

background = "#171717"
dark_background = "#101010"
darker_background = "#0a0a0a"
lighter_background = "#262626"

foreground = "#d4d4d4"
dark_foreground = "#8a8a8a"
light_foreground = "#eaeaea"
bright_foreground = "#fafafa"

red = "#ff2e3f"
yellow = "#ffca00"
orange = "#ffbc56"
green = "#0dbe4e"
cyan = "#08c0ef"
blue = "#009fff"
magenta = "#e130ac"
brown = "#a3713d"

bright_red = "#ff2e3f"
bright_yellow = "#ffca00"
bright_green = "#86c427"
bright_cyan = "#08c0ef"
bright_blue = "#009fff"
bright_magenta = "#e130ac"
